Args = \
  -H:+ReportExceptionStackTraces \
  --no-fallback \
  -H:+UnlockExperimentalVMOptions \
  -H:+AllowDeprecatedInitializeAllClassesAtBuildTime \
  --initialize-at-build-time= \
  --initialize-at-run-time=org.msgpack.core.buffer.DirectBufferAccess \
  -H:IncludeResources=org/pkl/core/stdlib/.*\\.pkl \
  -H:IncludeResourceBundles=org.pkl.core.errorMessages \
  -H:IncludeResourceBundles=org.pkl.parser.errorMessages \
  -H:MaxRuntimeCompileMethods=1800 \
  -H:+EnforceMaxRuntimeCompileMethods \
  --features=io.github.arlol.pkl.svm.InitFeature
