Args = \
  --initialize-at-build-time=org.pkl \
  --initialize-at-build-time=org.organicdesign.fp \
  --initialize-at-build-time=org.snakeyaml.engine \
  --features=io.github.arlol.pkl.svm.InitFeature
